### DISCUSSION TITLE
Compulsory adding authors

### DISCUSSION THREAD

**Discussion by zhenyuan0502** [auroral-ui/hexo-theme-aurora#47] [Q&A] [answered]
Hi bro,
I have tried to install this new theme, the steps have been followed but I got this message

    INFO Thanks for using Aurora v1.1.2
    INFO Check out the repo at: https://github.com/auroral-ui/hexo-theme-aurora
    INFO  Validating config
    INFO  Start processing
    FATAL {
      err: TypeError: Cannot read property 'Nguyên Lưu (Alfred - Yuan)' of null
          at authorMapper (C:\Users\Heisenberg\Documents\blog_zhenyuan0502\blog\node_modules\hexo-theme-aurora\scripts\lib\helpers\mapper.js:41:50)
          at postMapper (C:\Users\Heisenberg\Documents\blog_zhenyuan0502\blog\node_modules\hexo-theme-aurora\scripts\lib\helpers\mapper.js:33:13)
          at C:\Users\Heisenberg\Documents\blog_zhenyuan0502\blog\node_modules\hexo-theme-aurora\scripts\lib\generators\post.js:33:21
          at _Query.forEach (C:\Users\Heisenberg\Documents\blog_zhenyuan0502\blog\node_modules\warehouse\lib\query.js:36:7)
          at PostGenerator.transform (C:\Users\Heisenberg\Documents\blog_zhenyuan0502\blog\node_modules\hexo-theme-aurora\scripts\lib\generators\post.js:32:15)
          at new PostGenerator (C:\Users\Heisenberg\Documents\blog_zhenyuan0502\blog\node_modules\hexo-theme-aurora\scripts\lib\generators\post.js:13:10)
          at generator (C:\Users\Heisenberg\Documents\blog_zhenyuan0502\blog\node_modules\hexo-theme-aurora\scripts\lib\generators\index.js:91:19)
          at Hexo.<anonymous> (C:\Users\Heisenberg\Documents\blog_zhenyuan0502\blog\node_modules\hexo-theme-aurora\scripts\lib\generators\index.js:79:12)
          at Hexo.tryCatcher (C:\Users\Heisenberg\Documents\blog_zhenyuan0502\blog\node_modules\bluebird\js\release\util.js:16:23)
          at Hexo.<anonymous> (C:\Users\Heisenberg\Documents\blog_zhenyuan0502\blog\node_modules\bluebird\js\release\method.js:15:34)

The issue is, when _config.auroa not existed any author, the error will be thrown

    #! ---------------------------------------------------------------
    #! Authors Configs
    #！ @docs https://obsidianext.tridiamond.tech/guide/authors.html
    #! ---------------------------------------------------------------
    authors:

In my sense, I believe that it should be optional, as no authors defined, blog author would be caught up

**Comment by bennyxguo** [comment]
@zhenyuan0502 This setup is like this,  if you want the author to be yourself, you don't need to configure the author in the post's Front-Meta. 

If you want to add an author for your post, you have two ways, one is add a preset in the configuration file, then link it to your post by adding a "key" to the author property.

If you don't want to configure the author, then you can add the  author manually in the Front-Meta by using this template:
```yaml
---
title: Article Title
date: 2020-08-15 18:49:36
tags:
  - Tag
categories:
  - Cate
cover: https://cover.png
author:
  name: Tom
  link: https://tridiamond.tech
  avatar: https://avatar.png
---
```

I just published version 1.2.0, the author template had changed to this for version 1.2.0:

```yaml
# In configuration file:
authors:
  TriDiamond:
    name: TriDiamond
    avatar: https://up.enterdesk.com/edpic_source/44/ff/3d/44ff3d6bd2819d524facfcc33205d4cd.jpg
    link: https://github.com/TriDiamond,
    description: 'Think like an artist, code like an artisan.'
    socials:
      github: https://tridiamond.tech

# In Front-Meta
author:
  name: TriDiamond
  avatar: https://up.enterdesk.com/edpic_source/44/ff/3d/44ff3d6bd2819d524facfcc33205d4cd.jpg
  link: https://github.com/TriDiamond,
  description: 'Think like an artist, code like an artisan.'
  socials:
      github: https://tridiamond.tech
```

For more documentation go here: https://aurora.tridiamond.tech/guide/plugins.html#multiple-authors

**Comment by zhenyuan0502** [comment]
@TriDiamond Thank you for your response.
Just to be sure the context, my article before migration look like this

    title: Con đường đến với lập trình
    author: Nguyên Lưu (Alfred - Yuan)
    tags:
    
      - about
        categories:
      - Personal
        date: 2021-03-28 22:45:00

and my configuration look like this with null authors:

    site:
      subtitle: TriDiamond's Blog
      author: 三钻
      nick: TriDiamond
      description: 一位正在重塑知识的技术人 <br /> @ <b>公众号：技术银河</b>
      language: en
      multi_language: true
      logo: https://img-blog.csdnimg.cn/20210313122054101.png
      avatar: https://img-blog.csdnimg.cn/20210313122054101.png
      beian:
        number: ''
        link: ''
    
    #! ---------------------------------------------------------------
    #! Authors Configs
    #！ @docs https://obsidianext.tridiamond.tech/guide/authors.html
    #! ---------------------------------------------------------------
    authors:

Then it will throw the above exception.

Although I read `multiple authors` before, and I've left it with null `authors` field, as I thought it will get ***blog owner references to default author*** basically. If it need to be declared, I think it should have a flag, such like included_blog_owner to avoid rewriting info.

    authors:
        included_blog_owner: true

**Comment by bennyxguo** [comment, marked as answer]
@zhenyuan0502 
The concept is like this, as the default author, there is no need to write the author over and over in every post's markdown file. Therefore, in the site configure, there is a author property to set the default blog author.

Once that is set, all your posts will inherit this author as the "default" author, unless specified. This makes more sense, because if your post is posted by the default author, you won't need to change anything. If the post is from another author and you want to credit that. Perhaps you are a community you guys have multiple authors. Then setup the "multi-author".

Answer to your question, basically if you don't want to declare something, from my understanding is not setting that value at all, instead of having users to set a `null`. Making new posts and have user to write a `author: null` to every post is too much of a trouble. However the author property in the site config does make the logo text of the theme. If you don't want that, you want a different author name for the articles. Then setup a general author info in the authors setup, use a simple text key like `Alfred`:

```yaml
#! ---------------------------------------------------------------
#! Authors Configs
#！ @docs https://obsidianext.tridiamond.tech/guide/authors.html
#! ---------------------------------------------------------------
authors:
  Alfred:
    name: Nguyên Lưu (Alfred - Yuan)
    link:
    avatar: https://up.enterdesk.com/edpic_source/44/ff/3d/44ff3d6bd2819d524facfcc33205d4cd.jpg
    description: 'Think like an artist, code like an artisan.'
    socials:
      github: https://tridiamond.tech
```

Then in your Front-Meta, just use:

```yaml
title: Con đường đến với lập trình
author: Alfred
tags:
  - about
    categories:
  - Personal
    date: 2021-03-28 22:45:00
```

That's it~

If you want to just used the author of the site, should edit your configuration like this:

For the theme config `_config.aurora.yml`
```yaml
site:
  subtitle: Alfred 's Blog
  author: Nguyên Lưu
  nick: Alfred - Yuan
  description: xxxxxx
  language: en
  multi_language: true
  logo: https://img-blog.csdnimg.cn/20210313122054101.png
  avatar: https://img-blog.csdnimg.cn/20210313122054101.png
  beian:
    number: ''
    link: ''
```

Then in your Front-Meta, just use:

```yaml
title: Con đường đến với lập trình
tags:
  - about
    categories:
  - Personal
    date: 2021-03-28 22:45:00
```
