### ISSUE TITLE
Latex数学公式

### ISSUE THREAD

**Issue by BetterOIer** [auroral-ui/hexo-theme-aurora#211]
不能使用Latex公式

**Comment by shengpotxun** [comment]
主题根目录下终端执行 npm install hexo-filter-mathjax
根目录下_config.yml中加入一些设置语言
```
mathjax:
  tags: none               # or 'ams' or 'all'
  single_dollars: true     # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9           # relative CJK char width
  normal_width: 0.6        # relative normal (monospace) width
  append_css: true         # add CSS to every page
  every_page: false        # if true, every page will be rendered by mathjax regardless the `mathjax` setting in Front-matter of 
```
