### ISSUE TITLE
从 1.x 升级到 2.x 后代码高亮失效了

### ISSUE THREAD

**Issue by joshleeeeee** [auroral-ui/hexo-theme-aurora#274]
升级后代码块效果如下：

<img width="911" alt="image" src="https://github.com/auroral-ui/hexo-theme-aurora/assets/62055946/69b317fe-71d3-44ba-9655-45531eda9f2e">

我的`_config.yml`中代码高亮的设置：
``` yml
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
```
