### ISSUE TITLE
2.4.0版本标签搜索页面问题

### ISSUE THREAD

**Issue by Sang-Buster** [auroral-ui/hexo-theme-aurora#326]
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/97267956/591ec143-cf61-4866-94f4-4a0379a85084)

tag card是浮动的，网页往下拉莫名其妙会出现最近评论card， 拉到底或者往上拉就会消失。

---

还有一个小修复，footer navigation手机版下的css应该中心
```css
- .text-ob-normal{color:var(--text-normal)}
+ .text-ob-normal{justify-content: center;color:var(--text-normal)}
```
