### ISSUE TITLE
SEO优化之文章内容页面的description和keywords不生效

### ISSUE THREAD

**Issue by zjcscut** [auroral-ui/hexo-theme-aurora#347]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] (是否与都个问题有有关，请详细描述)

文章内容页面的页面中的meta中的description和keywords不生效，使用了全局配置中的description和keywords。例如：

```yml
---
title: 基于Canal和Kafka实现MySQL的Binlog近实时同步
date: 2020-03-07 00:47:46
album: 中间件专栏
tags:
  - Middleware
  - Canal
categories:
  - Middleware
description: 基于Canal和Kafka实现MySQL的Binlog近实时同步 - 中间件 - Throwable
keywords:
  - Canal
  - Kafka
  - Binlog
  - MySQL
cover: https://cdn.vlts.cn/articles/b6f47bd91065b96a6249fdcd02e0ee3e.webp
---
```

**Describe the solution you'd like**
A clear and concise description of what you want to happen.（描述想要的效果）

文章的front-matter中的author、description和keywords如果定义了，覆盖全局配置的author、description和keywords

**Additional context or screenshots**
Add any other context or screenshots about the feature request here.（附加信息或者截图）

![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/13879735/1b5fb6b0-f22e-45bd-b074-829013f0c35b)

文章：https://vlts.cn/post/canal-kafka-mysql-binlog-sync-guide
