### ISSUE TITLE
升级2.5.0后Github Action构建OOM，hexo g命令执行内存溢出

### ISSUE THREAD

**Issue by zjcscut** [auroral-ui/hexo-theme-aurora#366]
Github Action脚本如下：
```yml
name: Deploy Hexo Blog

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Auto Deploy Hexo Blog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Clean Hexo
        run: npx hexo clean

      - name: Build Hexo
        run: |
          npx hexo generate

      - name: Deploy Hexo
        run: |
          npx hexo deploy
```

在2.5.0版本前，此脚本构建和发布没有异常，升级2.5.0后跑到hexo g命令控制台显示OOM，日志如下：

![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/13879735/af22b3ec-790a-4149-aeaa-b8baf368283a)
