### ISSUE TITLE
代码高亮未启用

### ISSUE THREAD

**Issue by vanhiupun** [auroral-ui/hexo-theme-aurora#367]
代码高亮好像没有启用（之前v2.4.3好像也没有，可能是我设置的问题）
````
```css
[type='radio'] {
  margin: 20px 0px 20px 0px;
}
```
````

<img src=https://cdn.jsdelivr.net/gh/vanhiupun/pic@1.0/img/202309131340137.png width=60% />

```yaml
### _config.aurora.yml
shiki:
  enable: true
  theme: vitesse-dark
  backgroundColor: '#1a1a1a'
### _config.yml
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: false
  line_number: true
  tab_replace: false
```

**Comment by bennyxguo** [comment]
试试把陪护改成这样：
```yml
### _config.aurora.yml
shiki:
  enable: true
  theme: vitesse-dark
  backgroundColor: '#1a1a1a'

### _config.yml
highlight:
  enable: false
prismjs:
  enable: false
```

确保你更新了 hexo-plugin-aurora 到版本 v1.8.2+, 可以跑一下这个：

```shell
npm install hexo-theme-aurora@latest hexo-plugin-aurora@latest
```

然后一定要跑这个命令：

```shell
hexo clean && hexo g
```

**Comment by vanhiupun** [comment]
按照上面操作之后，代码高亮还是一样没有启用

**Comment by vanhiupun** [comment]
当我将
`shiki`设置为`enable: false`
`prismjs`设置为`enable: true`时

重新运行 
```bash
hexo clean && hexo g
```
代码高亮依旧未启用，因此我怀疑是其他问题

```json
  "dependencies": {
    "hexo": "^7.0.0-rc2",
    "hexo-deployer-git": "^4.0.0",
    "hexo-filter-mathjax": "^0.9.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-plugin-aurora": "^1.8.2",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.1.1",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-aurora": "^2.5.0",
    "hexo-theme-landscape": "^1.0.0"
  }
```

**Comment by vanhiupun** [comment]
找到原因了，当我修改`package.json`,将hexo版本设置为6.3.0时，重新生成代码高亮就回来了
```yaml
...
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "hexo": "^6.3.0",
...
```

**Comment by bennyxguo** [comment]
当前脚本没有支持 7.0，而且 7.0 也是预览版呢。先用 6.x 就好。

**Comment by xiaoyuebao** [comment]
@Theo-Messi 看看你的hexo版本，[禁用代码](https://hexo.io/zh-cn/docs/syntax-highlight#%E7%A6%81%E7%94%A8)

禁用
v7.0.0及以下：
```
# _config.yml
highlight:
  enable: false
prismjs:
  enable: false
```
v7.0.0及以上：
```
# _config.yml
syntax_highlighter: # empty
```

**Comment by xiaoyuebao** [comment]
看看你的hexo版本，[禁用代码](https://hexo.io/zh-cn/docs/syntax-highlight#%E7%A6%81%E7%94%A8)

禁用
v7.0.0及以下：
```
# _config.yml
highlight:
  enable: false
prismjs:
  enable: false
```
v7.0.0及以上：
```
# _config.yml
syntax_highlighter: # empty
```
