### ISSUE TITLE
代码高亮有问题，背景色影响了主题

### ISSUE THREAD

**Issue by twitf** [auroral-ui/hexo-theme-aurora#390]
> 我标注出来了你可以看下

![Snipaste_2023-09-19_15-03-13](https://github.com/auroral-ui/hexo-theme-aurora/assets/23697073/86efdaf0-0bc1-4528-983a-1146de9c40c0)

**Comment by bennyxguo** [comment]
对那些padding 确实没有按照背景颜色来。下一个版本修复。

**Comment by bennyxguo** [comment]
@twitf 这个问题是你的配置问题。我配置了一下没有你这个问题。使用下面这个配置：

```yml
#! ---------------------------------------------------------------
#! Highlighter Shiki
#! ---------------------------------------------------------------
shiki:
  enable: true
  theme: "material-theme-palenight" #主题名
```

**Comment by twitf** [comment]
我觉得你那个不是最新版本，我现在时这样处理的：`/**background-color:var(--bg-accent-05);*/`

```css
.post-html p code,.post-html li code {
    margin: 0;
    font-size: .85em;
    overflow-wrap: break-word;
    /**background-color:var(--bg-accent-05);*/
    word-wrap: break-word;
    padding: .1rem .3rem;
    border-radius: .3rem;
    color: var(--text-accent)!important
}
```

**Comment by bennyxguo** [comment]
我用的就是版本 2.5.3 哦

**Comment by zhangzhishun** [comment]
我也遇到这个问题了   现在最新的版本是2.5.2   

配置了：
#! ---------------------------------------------------------------
#! Highlighter Shiki
#! ---------------------------------------------------------------
shiki:
  enable: true
  theme: "material-theme-palenight" #主题名
也不可以

**Comment by bennyxguo** [comment]
> 我也遇到这个问题了 现在最新的版本是2.5.2
> 
> 配置了： #! --------------------------------------------------------------- #! Highlighter Shiki #! --------------------------------------------------------------- shiki: enable: true theme: "material-theme-palenight" #主题名 也不可以

你可以截图看看你的配置吗？你的配置的格式感觉不对。shiki 后面的两个参数需要有缩紧两个空格才行。

```yaml
#! ---------------------------------------------------------------
#! Highlighter Shiki
#! ---------------------------------------------------------------
shiki:
  enable: true
  theme: "material-theme-palenight" #主题名
```
