### ISSUE TITLE
[bug]twiko关闭最近评论后不能正常工作

### ISSUE THREAD

**Issue by Tim-Saijun** [auroral-ui/hexo-theme-aurora#406]
在配置文件中把recentcomment关闭，则**不显示评论**（所有评论相关的功能包括文章访问量）；打开则一切正常，再关闭则又不显示评论；可稳定复现。
twiko部署在netlify上，配置文件如下：
```yml

# For local development only!
gitalk:
  enable: false
  autoExpand: true
  clientID: ''
  clientSecret: ''
  repo: '' ## dev-blo-comments
  owner: '' ## owner name
  admin: [''] ## ['admin_name']
  id: uid
  language: en
  distractionFreeMode: true
  recentComment: true
  proxy: ''

# Valine comment plugin (recommended!)
# see https://valine.js.org/quickstart.html
valine:
  enable: false
  app_id:
  app_key:
  avatar: ''
  placeholder: Leave your thoughts behind~
  visitor: true
  lang: en
  avatarForce: false
  meta: ['nick', 'mail']
  requiredFields: ['nick', 'mail']
  admin: '' # admin username
  recentComment: true

# Twikoo comment plugin
# see https://twikoo.js.org/quick-start.html
twikoo:
  enable: true
  recentComment: true
  visitor: true
  envId: https://***oo # 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
  # region: ap-guangzhou # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
  lang: 'zh' # 用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/client/utils/i18n/index.js

# Waline comment plugin
# see https://waline.js.org/guide/get-started/
waline:
  enable: false
  recentComment: false
  reaction: false
  login: 'disable'
  meta: ['nick', 'mail','link']
  requiredMeta: ['nick']
  commentSorting: 'latest'
  wordLimit: 1000
  imageUploader: false
  pageSize: 10
  serverURL: '' # 填写服务端地址

# Enable Busuanzi statistic plugin
# see http://ibruce.info/2015/04/04/busuanzi/
busuanzi:
  enable: true
```
