### ISSUE TITLE
v2.5.3 代码高亮异常

### ISSUE THREAD

**Issue by FHangH** [auroral-ui/hexo-theme-aurora#433]
_config.yml的设置
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/49579735/c56b4360-4601-4263-9441-45a31ff1e728)

_config.aurora.yml
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/49579735/da5a71e9-41ec-47a4-8d95-9912949498a4)

重新生成后的代码高亮好像没有正确显示
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/49579735/cd286444-d47f-4e6e-b0d0-d1ae8edb9ea3)

我也看了文档里的示例博客，也是相同的情况，这个地方是还没有完善吗？还是需要其他额外的设置？
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/49579735/90d77962-f18b-472a-8a13-fdde37a2ea1e)

**Comment by Apa7-zero** [comment]
解决了么

**Comment by xiaoyuebao** [comment]
看看你的hexo版本，[禁用代码](https://hexo.io/zh-cn/docs/syntax-highlight#%E7%A6%81%E7%94%A8)

禁用
v7.0.0及以下：
```
# _config.yml
highlight:
  enable: false
prismjs:
  enable: false
```
v7.0.0及以上：
```
# _config.yml
syntax_highlighter: # empty
```

**Comment by xiaoyuebao** [comment]
@Apa7-zero 看看你的hexo版本，[禁用代码](https://hexo.io/zh-cn/docs/syntax-highlight#%E7%A6%81%E7%94%A8)

禁用
v7.0.0及以下：
```
# _config.yml
highlight:
  enable: false
prismjs:
  enable: false
```
v7.0.0及以上：
```
# _config.yml
syntax_highlighter: # empty
```
