### ISSUE TITLE
Desktop menu not showing

### ISSUE THREAD

**Issue by DarkXero-dev** [auroral-ui/hexo-theme-aurora#442]
I have added external links in menu they only show on mobile site not on desktop one. On Desktop shows clickable empty space.. This is [**Site Link**](https://blog.xerolinux.org)

Menu area in config
```YAML
menu:
  About: false
  Tags: false
  Archives: false
  XeroLinux:
     name: 'XeroLinux'
     path: 'https://xerolinux.xyz'
  Forums:
     name: 'XeroLinux Forums'
     path: 'https://forum.xerolinux.xyz'
  RSS:
     name: 'RSS Feed'
     path: 'https://blog.xerolinux.xyz/atom.xml'
```
