### ISSUE TITLE
[bug] 求助：自定义菜单无法显示名称

### ISSUE THREAD

**Issue by HaloSense** [auroral-ui/hexo-theme-aurora#457]
我按照[这个链接](https://aurora.tridiamond.tech/cn/configs/menu.html)的教程配置自定义菜单，`_config,aurora.yml` 相关配置如下：
```YAML
#! ---------------------------------------------------------------
#! Menu Configs
#！ @docs https://aurora.tridiamond.tech/guide/menu.html
#! ---------------------------------------------------------------
menu:
  About: true
  Tags: true
  Archives: true
  Friends: false
  bilibili: 
    name: 'bilibili'
    i18n: 
      cn: B站个人页
      en: Bilibili
    path: 'https://space.bilibili.com/4138864'
  github: 
    name: 'GitHub'
    i18n: 
      cn: GitHub
      en: GitHub
    path: 'https://github.com/HaloSense'
```
在本地使用`hexo server`跑起来后效果如下图
![image](https://github.com/user-attachments/assets/2d347261-b12a-4b59-935c-be4bfe6582bb)
可以看到确实添加了一个外链，鼠标点击也可以跳转，但是没有文本。

第一次使用hexo和aurora主题搭建个人站，很多东西都不懂，请不吝指导，谢谢。
