### ISSUE TITLE
无法使用.html后缀

### ISSUE THREAD

**Issue by SuiKevin** [auroral-ui/hexo-theme-aurora#459]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
设置permalink为：/post/:postlink.html后，会在public/post/目录中生成.html的文章。
但是在访问文章时页面的url依然没有.html，文章链接为https://domain.com/post/article_postlink。
添加.html后页面无法加载内容，访问不到api/article_postlink.html.json

**需要添加文章链接.html后缀，以便SEO优化**

**Additional context or screenshots**
**_config.yml**
```
permalink: /post/:postlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
```
**article.md**
```
---
title: Article Title
postlink: article_title
---
```
