### ISSUE TITLE
[bug]第三方作者会直接使用custom_socials

### ISSUE THREAD

**Issue by kcn3388** [auroral-ui/hexo-theme-aurora#71]
![image](https://user-images.githubusercontent.com/25716090/115366811-33ec0800-a1f8-11eb-8a36-2866cdf75bc2.png)
```
custom_socials:
  #! Example:
  #! --- Using SVG
  bilibili:
    icon: /svg/bilibili-fill.svg
    link: 
    icon: /svg/page.svg
    link: 
```
